# Generated by Django 2.2.7 on 2019-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_doctorsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Enter your email address', max_length=100)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('section', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='accounts_patient',
        ),
    ]
