# Generated by Django 2.2.7 on 2019-12-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191217_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_patientmodel',
            name='diseased',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accounts_patientmodel',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accounts_patientmodel',
            name='nationality',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accounts_patientmodel',
            name='place_of_birth',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
