# Generated by Django 2.2.7 on 2019-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191217_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_doctorsmodel',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts_doctorsmodel',
            name='section',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
