# Generated by Django 2.2.7 on 2019-12-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191218_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_patientmodel',
            name='diseased',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
