# Generated by Django 2.2.7 on 2019-12-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191218_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts_doctorsmodel',
        ),
    ]
